import type { Lang } from "@/content/i18n";

export type PrivacyContent = {
  title: string;
  backToHome: string;
  intro: string;

  sections: {
    controller: {
      title: string;
      body: string;
    };
    dataCollected: {
      title: string;
      body: string;
    };
    purpose: {
      title: string;
      body: string;
    };
    legalBasis: {
      title: string;
      body: string;
    };
    retention: {
      title: string;
      body: string;
    };
    hosting: {
      title: string;
      body: string;
    };
    rights: {
      title: string;
      body: string;
    };
    contact: {
      title: string;
      body: string;
    };
  };
};

export const privacyContent: Record<Lang, PrivacyContent> = {
  en: {
    title: "Privacy Policy",
    backToHome: "Back to home",
    intro:
      "This page explains how personal data is handled when you visit this website or get in touch.",

    sections: {
      controller: {
        title: "Data controller",
        body:
          "The data controller is Mario Coppola. For any privacy-related request, you can contact: mariocoppo91@gmail.com",
      },
      dataCollected: {
        title: "Data collected",
        body:
          "This website may process the email address and message you provide when contacting me, as well as basic technical data automatically generated by the hosting provider (such as IP address and access logs).",
      },
      purpose: {
        title: "Purpose of processing",
        body:
          "Personal data is processed solely to respond to inquiries, maintain communication related to professional requests, and ensure the security and proper functioning of the website.",
      },
      legalBasis: {
        title: "Legal basis",
        body:
          "Processing is based on your request to be contacted and on the legitimate interest in ensuring secure and reliable website operation.",
      },
      retention: {
        title: "Data retention",
        body:
          "Messages and related data are kept only for the time necessary to handle the request and any follow-up communication, unless further retention is required for legitimate reasons.",
      },
      hosting: {
        title: "Hosting",
        body:
          "The website is hosted by a third-party provider that may process technical data (such as IP address and logs) strictly for infrastructure and security purposes.",
      },
      rights: {
        title: "Your rights",
        body:
          "You have the right to request access, correction, deletion, or restriction of your personal data. You may also object to processing or request data portability where applicable.",
      },
      contact: {
        title: "Contact",
        body:
          "For any privacy-related request, you can contact: mariocoppo91@gmail.com",
      },
    },
  },

  it: {
    title: "Informativa sulla privacy",
    backToHome: "Torna alla home",
    intro:
      "Questa pagina descrive come vengono trattati i dati personali quando visiti il sito o mi contatti.",

    sections: {
      controller: {
        title: "Titolare del trattamento",
        body:
          "Il titolare del trattamento è Mario Coppola. Per qualsiasi richiesta relativa alla privacy puoi contattare: mariocoppo91@gmail.com",
      },
      dataCollected: {
        title: "Dati raccolti",
        body:
          "Il sito può trattare l'indirizzo email e il messaggio forniti in caso di contatto, oltre a dati tecnici generati automaticamente dal provider di hosting (come indirizzo IP e log di accesso).",
      },
      purpose: {
        title: "Finalità del trattamento",
        body:
          "I dati personali vengono trattati esclusivamente per rispondere alle richieste ricevute, mantenere comunicazioni di natura professionale e garantire la sicurezza e il corretto funzionamento del sito.",
      },
      legalBasis: {
        title: "Base giuridica",
        body:
          "Il trattamento si basa sulla richiesta dell'interessato di essere contattato e sul legittimo interesse a garantire il funzionamento sicuro e affidabile del sito.",
      },
      retention: {
        title: "Conservazione dei dati",
        body:
          "I messaggi e i dati correlati vengono conservati per il tempo necessario a gestire la richiesta e l'eventuale comunicazione successiva, salvo esigenze ulteriori legittime.",
      },
      hosting: {
        title: "Hosting",
        body:
          "Il sito è ospitato presso un provider terzo che può trattare dati tecnici (come indirizzo IP e log) esclusivamente per finalità infrastrutturali e di sicurezza.",
      },
      rights: {
        title: "Diritti dell'interessato",
        body:
          "Hai il diritto di richiedere accesso, rettifica, cancellazione o limitazione dei dati personali. Puoi inoltre opporti al trattamento o richiedere la portabilità dei dati quando applicabile.",
      },
      contact: {
        title: "Contatti",
        body:
          "Per qualsiasi richiesta relativa alla privacy puoi scrivere a: mariocoppo91@gmail.com",
      },
    },
  },
};